baseURL: http://adenosinetp10.github.io/
languageCode: en-us
title: adenosinetp10
theme: "PaperModX"

enableRobotsTXT: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  defaultTheme: auto

params:
  TocSide: 'left'

  ShowShareButtons: true

  homeInfoParams:
        Title: Hi
        Content: >
            On the Internet I go by the name <mark>adenosinetp10</mark> mostly.

            I like coding, watching anime and reading comics.

            I like to play computer games as well, mostly single player ones.

  socialIcons: # optional
      - name: "Telegram-simple"
        url: "https://t.me/adenosinetp10"
      - name: "GitHub-simple"
        url: "https://github.com/adenosinetp10"
      - name: "HackerRank"
        url: "https://hackerrank.com/adenosinetp10"
      - name: "AniList"
        url: "https://anilist.co/adenosinetp10"


menu:
  main:

    - name: "Cool Sites"
      url: "/cool-sites"
      params:
        external: false

    - name: "Posts"
      url: "/posts"
      params:
        external: false

    - name: "Memes"
      url: "/memes"
      params:
        external: false

    