baseURL: http://adenosinetp10.github.io/
languageCode: en-us
title: adenosinetp10
theme: "PaperModX"

params:
  defaultTheme: auto
  TocSide: 'right'

  homeInfoParams:
        Title: Hi
        Content: I'm adenosinetp10

  socialIcons: # optional
      - name: "Telegram"
        url: "https://t.me/adenosinetp10"
      - name: "GitHub"
        url: "https://github.com/adenosinetp10"

