baseURL: http://adenosinetp10.github.io/
languageCode: en-us
title: adenosinetp10
theme: "PaperModX"

params:
  defaultTheme: auto
  TocSide: 'right'

  homeInfoParams:
        Title: Hi
        Content: On the Internet I go by the name `adenosinetp10` mostly. I like coding, watching anime and reading comics. I like to play computer games as well, mostly single player ones.

  socialIcons: # optional
      - name: "Telegram"
        url: "https://t.me/adenosinetp10"
      - name: "GitHub"
        url: "https://github.com/adenosinetp10"

